server:
  port: 3000

spring:
  application:
    name: inventory-management
  datasource:
    url: jdbc:mariadb://localhost:3306/inventory_management
    driver-class-name: org.mariadb.jdbc.Driver
    username: historymanager
    password: historymanager1!
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.MariaDBDialect
