import {defineStore} from "pinia";

export const useInventoryStore = defineStore('inventory', {
    state: () => {
        return {
            count: 0,
            purchaseGridHeaders: [
                { title: '구매처', editable: true, align: 'center', key: 'purchasePlace' },
                { title: '이미지', align: 'center', key: 'purchaseImage' },
                { title: '카테고리', align: 'center', key: 'category' },
                { title: '상품명', align: 'center', key: 'productName' },
                { title: '메모', align: 'center', key: 'productMemo' },
                { title: '가격', align: 'center', key: 'productPrice' },
                { title: '수량', align: 'center', key: 'productQty' },
                { title: '구매일', align: 'center', key: 'purchaseDate' },
            ],
            purchaseGridItems: [
                {
                    purchaseId: 1,
                    purchasePlace: '쿠팡',
                    purchaseImage: '이미지 url1',
                    category: '생활용품',
                    productName: '휴대폰충전기',
                    productMemo: '1미터짜리로 삼',
                    productPrice: 45000,
                    productQty: 1,
                    purchaseDate: '2024-07-02',
                },
                {
                    purchaseId: 2,
                    purchasePlace: '11번가',
                    purchaseImage: '이미지 url2',
                    category: '생활용품',
                    productName: '로지텍마우스',
                    productMemo: 'G304',
                    productPrice: 50000,
                    productQty: 1,
                    purchaseDate: '2024-07-04',
                },
                {
                    purchaseId: 3,
                    purchasePlace: '옥션',
                    purchaseImage: '이미지 url3',
                    category: '전자제품',
                    productName: '헤드폰',
                    productMemo: '노이즈캔슬링 기능',
                    productPrice: 100000,
                    productQty: 1,
                    purchaseDate: '2024-07-05',
                },
                {
                    purchaseId: 4,
                    purchasePlace: 'G마켓',
                    purchaseImage: '이미지 url4',
                    category: '생활용품',
                    productName: '물티슈',
                    productMemo: '대용량 100매',
                    productPrice: 20000,
                    productQty: 2,
                    purchaseDate: '2024-07-06',
                },
                {
                    purchaseId: 5,
                    purchasePlace: '네이버쇼핑',
                    purchaseImage: '이미지 url5',
                    category: '패션',
                    productName: '운동화',
                    productMemo: '사이즈 270',
                    productPrice: 80000,
                    productQty: 1,
                    purchaseDate: '2024-07-07',
                },
                {
                    purchaseId: 6,
                    purchasePlace: '위메프',
                    purchaseImage: '이미지 url6',
                    category: '식품',
                    productName: '아몬드',
                    productMemo: '1kg',
                    productPrice: 15000,
                    productQty: 1,
                    purchaseDate: '2024-07-08',
                },
                {
                    purchaseId: 7,
                    purchasePlace: '티몬',
                    purchaseImage: '이미지 url7',
                    category: '전자제품',
                    productName: '키보드',
                    productMemo: '기계식 키보드',
                    productPrice: 70000,
                    productQty: 1,
                    purchaseDate: '2024-07-09',
                },
                {
                    purchaseId: 8,
                    purchasePlace: '인터파크',
                    purchaseImage: '이미지 url8',
                    category: '서적',
                    productName: '자기계발서',
                    productMemo: '베스트셀러',
                    productPrice: 12000,
                    productQty: 1,
                    purchaseDate: '2024-07-10',
                },
                {
                    purchaseId: 9,
                    purchasePlace: '롯데홈쇼핑',
                    purchaseImage: '이미지 url9',
                    category: '생활용품',
                    productName: '청소기',
                    productMemo: '무선청소기',
                    productPrice: 200000,
                    productQty: 1,
                    purchaseDate: '2024-07-11',
                },
                {
                    purchaseId: 10,
                    purchasePlace: '현대백화점',
                    purchaseImage: '이미지 url10',
                    category: '가구',
                    productName: '의자',
                    productMemo: '인체공학적 디자인',
                    productPrice: 150000,
                    productQty: 1,
                    purchaseDate: '2024-07-12',
                },
                {
                    purchaseId: 11,
                    purchasePlace: '쿠팡',
                    purchaseImage: '이미지 url11',
                    category: '전자제품',
                    productName: '태블릿',
                    productMemo: '최신형',
                    productPrice: 300000,
                    productQty: 1,
                    purchaseDate: '2024-07-13',
                },
                {
                    purchaseId: 12,
                    purchasePlace: '11번가',
                    purchaseImage: '이미지 url12',
                    category: '생활용품',
                    productName: '비누',
                    productMemo: '천연 비누',
                    productPrice: 5000,
                    productQty: 5,
                    purchaseDate: '2024-07-14',
                },
                {
                    purchaseId: 13,
                    purchasePlace: '옥션',
                    purchaseImage: '이미지 url13',
                    category: '식품',
                    productName: '과자 세트',
                    productMemo: '여러 종류',
                    productPrice: 25000,
                    productQty: 1,
                    purchaseDate: '2024-07-15',
                },
                {
                    purchaseId: 14,
                    purchasePlace: 'G마켓',
                    purchaseImage: '이미지 url14',
                    category: '전자제품',
                    productName: '모니터',
                    productMemo: '4K 해상도',
                    productPrice: 400000,
                    productQty: 1,
                    purchaseDate: '2024-07-16',
                },
                {
                    purchaseId: 15,
                    purchasePlace: '네이버쇼핑',
                    purchaseImage: '이미지 url15',
                    category: '패션',
                    productName: '청바지',
                    productMemo: '사이즈 32',
                    productPrice: 60000,
                    productQty: 1,
                    purchaseDate: '2024-07-17',
                },
                {
                    purchaseId: 16,
                    purchasePlace: '위메프',
                    purchaseImage: '이미지 url16',
                    category: '생활용품',
                    productName: '샴푸',
                    productMemo: '500ml',
                    productPrice: 12000,
                    productQty: 1,
                    purchaseDate: '2024-07-18',
                },
                {
                    purchaseId: 17,
                    purchasePlace: '티몬',
                    purchaseImage: '이미지 url17',
                    category: '서적',
                    productName: '소설책',
                    productMemo: '베스트셀러',
                    productPrice: 15000,
                    productQty: 1,
                    purchaseDate: '2024-07-19',
                },
                {
                    purchaseId: 18,
                    purchasePlace: '인터파크',
                    purchaseImage: '이미지 url18',
                    category: '식품',
                    productName: '커피',
                    productMemo: '원두 1kg',
                    productPrice: 20000,
                    productQty: 1,
                    purchaseDate: '2024-07-20',
                },
                {
                    purchaseId: 19,
                    purchasePlace: '롯데홈쇼핑',
                    purchaseImage: '이미지 url19',
                    category: '가구',
                    productName: '책상',
                    productMemo: '사무용',
                    productPrice: 100000,
                    productQty: 1,
                    purchaseDate: '2024-07-21',
                },
                {
                    purchaseId: 20,
                    purchasePlace: '현대백화점',
                    purchaseImage: '이미지 url20',
                    category: '전자제품',
                    productName: '스마트워치',
                    productMemo: '피트니스 기능',
                    productPrice: 250000,
                    productQty: 1,
                    purchaseDate: '2024-07-22',
                },
                {
                    purchaseId: 21,
                    purchasePlace: '쿠팡',
                    purchaseImage: '이미지 url21',
                    category: '생활용품',
                    productName: '텀블러',
                    productMemo: '보온/보냉 기능',
                    productPrice: 30000,
                    productQty: 1,
                    purchaseDate: '2024-07-23',
                },
                {
                    purchaseId: 22,
                    purchasePlace: '11번가',
                    purchaseImage: '이미지 url22',
                    category: '패션',
                    productName: '티셔츠',
                    productMemo: '사이즈 L',
                    productPrice: 20000,
                    productQty: 2,
                    purchaseDate: '2024-07-24',
                },
                {
                    purchaseId: 23,
                    purchasePlace: '옥션',
                    purchaseImage: '이미지 url23',
                    category: '서적',
                    productName: '여행 가이드북',
                    productMemo: '유럽 여행',
                    productPrice: 25000,
                    productQty: 1,
                    purchaseDate: '2024-07-25',
                },
                {
                    purchaseId: 24,
                    purchasePlace: 'G마켓',
                    purchaseImage: '이미지 url24',
                    category: '식품',
                    productName: '초콜릿',
                    productMemo: '다크 초콜릿',
                    productPrice: 10000,
                    productQty: 3,
                    purchaseDate: '2024-07-26',
                },
                {
                    purchaseId: 25,
                    purchasePlace: '네이버쇼핑',
                    purchaseImage: '이미지 url25',
                    category: '전자제품',
                    productName: '블루투스 스피커',
                    productMemo: '휴대용',
                    productPrice: 50000,
                    productQty: 1,
                    purchaseDate: '2024-07-27',
                },
                {
                    purchaseId: 26,
                    purchasePlace: '위메프',
                    purchaseImage: '이미지 url26',
                    category: '생활용품',
                    productName: '주방용품 세트',
                    productMemo: '칼, 도마, 주걱 세트',
                    productPrice: 35000,
                    productQty: 1,
                    purchaseDate: '2024-07-28',
                },
                {
                    purchaseId: 27,
                    purchasePlace: '티몬',
                    purchaseImage: '이미지 url27',
                    category: '패션',
                    productName: '모자',
                    productMemo: '야구모자',
                    productPrice: 18000,
                    productQty: 1,
                    purchaseDate: '2024-07-29',
                },
                {
                    purchaseId: 28,
                    purchasePlace: '인터파크',
                    purchaseImage: '이미지 url28',
                    category: '전자제품',
                    productName: '게임 콘솔',
                    productMemo: '최신형',
                    productPrice: 400000,
                    productQty: 1,
                    purchaseDate: '2024-07-30',
                },
                {
                    purchaseId: 29,
                    purchasePlace: '롯데홈쇼핑',
                    purchaseImage: '이미지 url29',
                    category: '생활용품',
                    productName: '욕실매트',
                    productMemo: '미끄럼 방지',
                    productPrice: 12000,
                    productQty: 1,
                    purchaseDate: '2024-07-31',
                },
                {
                    purchaseId: 30,
                    purchasePlace: '현대백화점',
                    purchaseImage: '이미지 url30',
                    category: '식품',
                    productName: '와인',
                    productMemo: '레드와인',
                    productPrice: 50000,
                    productQty: 1,
                    purchaseDate: '2024-08-01',
                },
                {
                    purchaseId: 31,
                    purchasePlace: '쿠팡',
                    purchaseImage: '이미지 url31',
                    category: '패션',
                    productName: '백팩',
                    productMemo: '노트북 수납 가능',
                    productPrice: 60000,
                    productQty: 1,
                    purchaseDate: '2024-08-02',
                },
                {
                    purchaseId: 32,
                    purchasePlace: '11번가',
                    purchaseImage: '이미지 url32',
                    category: '서적',
                    productName: '요리책',
                    productMemo: '이탈리안 요리',
                    productPrice: 18000,
                    productQty: 1,
                    purchaseDate: '2024-08-03',
                },
                {
                    purchaseId: 33,
                    purchasePlace: '옥션',
                    purchaseImage: '이미지 url33',
                    category: '전자제품',
                    productName: '드론',
                    productMemo: '4K 카메라 탑재',
                    productPrice: 500000,
                    productQty: 1,
                    purchaseDate: '2024-08-04',
                },
                {
                    purchaseId: 34,
                    purchasePlace: 'G마켓',
                    purchaseImage: '이미지 url34',
                    category: '생활용품',
                    productName: '캠핑 의자',
                    productMemo: '접이식',
                    productPrice: 35000,
                    productQty: 2,
                    purchaseDate: '2024-08-05',
                },
                {
                    purchaseId: 35,
                    purchasePlace: '네이버쇼핑',
                    purchaseImage: '이미지 url35',
                    category: '패션',
                    productName: '선글라스',
                    productMemo: 'UV 차단',
                    productPrice: 20000,
                    productQty: 1,
                    purchaseDate: '2024-08-06',
                },
                {
                    purchaseId: 36,
                    purchasePlace: '위메프',
                    purchaseImage: '이미지 url36',
                    category: '서적',
                    productName: '역사책',
                    productMemo: '세계사',
                    productPrice: 25000,
                    productQty: 1,
                    purchaseDate: '2024-08-07',
                },
                {
                    purchaseId: 37,
                    purchasePlace: '티몬',
                    purchaseImage: '이미지 url37',
                    category: '식품',
                    productName: '치즈',
                    productMemo: '체다치즈 1kg',
                    productPrice: 30000,
                    productQty: 1,
                    purchaseDate: '2024-08-08',
                },
                {
                    purchaseId: 38,
                    purchasePlace: '인터파크',
                    purchaseImage: '이미지 url38',
                    category: '전자제품',
                    productName: '휴대용 충전기',
                    productMemo: '10000mAh',
                    productPrice: 20000,
                    productQty: 1,
                    purchaseDate: '2024-08-09',
                },
                {
                    purchaseId: 39,
                    purchasePlace: '롯데홈쇼핑',
                    purchaseImage: '이미지 url39',
                    category: '생활용품',
                    productName: '커튼',
                    productMemo: '암막 커튼',
                    productPrice: 40000,
                    productQty: 1,
                    purchaseDate: '2024-08-10',
                },
                {
                    purchaseId: 40,
                    purchasePlace: '현대백화점',
                    purchaseImage: '이미지 url40',
                    category: '패션',
                    productName: '시계',
                    productMemo: '방수 기능',
                    productPrice: 120000,
                    productQty: 1,
                    purchaseDate: '2024-08-11',
                },
                {
                    purchaseId: 41,
                    purchasePlace: '쿠팡',
                    purchaseImage: '이미지 url41',
                    category: '서적',
                    productName: '다이어리',
                    productMemo: '2024년 다이어리',
                    productPrice: 15000,
                    productQty: 1,
                    purchaseDate: '2024-08-12',
                },
                {
                    purchaseId: 42,
                    purchasePlace: '11번가',
                    purchaseImage: '이미지 url42',
                    category: '식품',
                    productName: '홍차',
                    productMemo: '잉글리시 블랙퍼스트',
                    productPrice: 10000,
                    productQty: 1,
                    purchaseDate: '2024-08-13',
                },
                {
                    purchaseId: 43,
                    purchasePlace: '옥션',
                    purchaseImage: '이미지 url43',
                    category: '전자제품',
                    productName: '프로젝터',
                    productMemo: '홈 시어터',
                    productPrice: 300000,
                    productQty: 1,
                    purchaseDate: '2024-08-14',
                },
                {
                    purchaseId: 44,
                    purchasePlace: 'G마켓',
                    purchaseImage: '이미지 url44',
                    category: '생활용품',
                    productName: '휴지통',
                    productMemo: '스테인리스',
                    productPrice: 20000,
                    productQty: 1,
                    purchaseDate: '2024-08-15',
                },
                {
                    purchaseId: 45,
                    purchasePlace: '네이버쇼핑',
                    purchaseImage: '이미지 url45',
                    category: '패션',
                    productName: '자켓',
                    productMemo: '가을용',
                    productPrice: 90000,
                    productQty: 1,
                    purchaseDate: '2024-08-16',
                },
                {
                    purchaseId: 46,
                    purchasePlace: '위메프',
                    purchaseImage: '이미지 url46',
                    category: '서적',
                    productName: '건강서적',
                    productMemo: '운동 방법',
                    productPrice: 18000,
                    productQty: 1,
                    purchaseDate: '2024-08-17',
                },
                {
                    purchaseId: 47,
                    purchasePlace: '티몬',
                    purchaseImage: '이미지 url47',
                    category: '식품',
                    productName: '샐러드',
                    productMemo: '혼합 샐러드',
                    productPrice: 8000,
                    productQty: 2,
                    purchaseDate: '2024-08-18',
                },
                {
                    purchaseId: 48,
                    purchasePlace: '인터파크',
                    purchaseImage: '이미지 url48',
                    category: '전자제품',
                    productName: 'USB 허브',
                    productMemo: '4포트 USB 3.0',
                    productPrice: 15000,
                    productQty: 1,
                    purchaseDate: '2024-08-19',
                },
                {
                    purchaseId: 49,
                    purchasePlace: '롯데홈쇼핑',
                    purchaseImage: '이미지 url49',
                    category: '생활용품',
                    productName: '베개',
                    productMemo: '메모리폼',
                    productPrice: 30000,
                    productQty: 2,
                    purchaseDate: '2024-08-20',
                },
                {
                    purchaseId: 50,
                    purchasePlace: '현대백화점',
                    purchaseImage: '이미지 url50',
                    category: '패션',
                    productName: '정장',
                    productMemo: '한 벌',
                    productPrice: 200000,
                    productQty: 1,
                    purchaseDate: '2024-08-21',
                },
            ],
        }
    },
    // could also be defined as
    // state: () => ({ count: 0 })
    actions: {
        increment() {
            this.count++
        },
        deleteGridItem(items) {
            for(let i in items){
                const index = this.purchaseGridItems.indexOf(items[i]);
                this.purchaseGridItems.splice(index, 1);
            }
        }
    },
})